name: Build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
        inlineScript: |
           Install-Module -Name Pester -Force
           Invoke-Pester './tests/*.tests.ps1' -OutputFile './test-reports/TEST-CI.xml' -OutputFormat 'NUnitXML'
        azPSVersion: 'latest'

    - name: Generate Pester Report
      uses: bart-jansen/nunit-reporter@add-pester-support
      if: always()
      with:
        path: ./test-reports/*.xml
        access-token:  ${{ secrets.GITHUB_TOKEN }}
